// Sources/snapview/Generator/RegistryGenerator.swift
import Foundation

enum RegistryGenerator {

  static func generate(
    entries: [PreviewEntry],
    imports: [String],
    appModule: String
  ) -> String {
    var allImports = Set(imports)
    allImports.insert("import SwiftUI")

    // Remove any existing @testable import of the app module to avoid duplication
    allImports.remove("@testable import \(appModule)")
    allImports.remove("import \(appModule)")

    let sortedImports = allImports.sorted()
    let importBlock = sortedImports.joined(separator: "\n")

    let entriesBlock = entries.map { entry in
      """
          Entry(name: "\(entry.name)") {
            AnyView(
              \(entry.body.split(separator: "\n").joined(separator: "\n        "))
            )
          },
      """
    }.joined(separator: "\n")

    return """
    // SnapViewRegistry.swift — auto-generated by snapview. Do not edit.
    \(importBlock)
    @testable import \(appModule)

    enum SnapViewRegistry {

      struct Entry {
        let name: String
        let body: @MainActor () -> AnyView
      }

      static let all: [Entry] = [
    \(entriesBlock)
      ]
    }
    """
  }
}
